accounts/urls.py
from django.urls import path
from .views import SignupView, UserLoginView, UserLogoutView

app_name = "accounts"

urlpatterns = [
    path("", UserLoginView.as_view(), name="login"),
    path("signup", SignupView.as_view(), name="signup"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

answer/urls.py
from django.urls import path
from .views import ProblemCreateView

app_name = "answer"

urlpatterns = [
    path("create/", ProblemCreateView.as_view(), name="create"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

home/urls.py
from django.urls import path
from .views import HomeView

app_name = "home"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

spellmade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("home/", include("home.urls")),
    path("answer/", include("answer.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime
# Create your models here.


class User(AbstractUser):
    email = models.EmailField("メールアドレス", unique=True)


class Problem(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="problems"
    )
    english = models.CharField(max_length=100)
    japanese = models.CharField(max_length=100)
    degree = models.IntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["placeholder"] = field.label

answer/forms.py
from django import forms
from accounts.models import Problem


class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ["english", "japanese", "degree"]

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login, authenticate
from .forms import SignupForm, LoginForm
from django.urls import reverse_lazy
from django.conf import settings

# Create your views here.


class SignupView(CreateView):
    form_class = SignupForm
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)
    template_name = "accounts/signup.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(self.request, user=user)
        return response


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = "accounts/login.html"


class UserLogoutView(LogoutView):
    success_url = reverse_lazy("accounts:signup")

answer/views.py
from django.shortcuts import render
from .forms import ProblemForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
# Create your views here.


class ProblemCreateView(CreateView):
    form_class = ProblemForm
    success_url = reverse_lazy("home:home")
    template_name = "answer/problemCreate.html"

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.utils import timezone
from .forms import PostForm

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html',{'post':post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from accounts.models import Problem

# Create your views here.


class HomeView(ListView):
    template_name = "home/home.html"
    model = Problem
    context_object_name = "problems"
    queryset = model.objects.select_related("user").order_by("-created_at")

blog/templates/blog/base.html
{% load static %}

<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu" ><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                <p>published: {{ post.published_date }}</p>
            </div>
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/_form.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="{{ submit_label }}">
</form>

templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-original">
    <div class="container-fluid d-flex justify-content-between nav-original-child">
        <div class="navbar-nav mr-auto left-item">
            <a>spellmade</a>
        </div>
        <div class="navbar-nav right-item">
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'answer:create' %}">Create</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Answer</a>
                    </li>
                    <div class="btn-group">
                        <button type="button" class="btn btn-success">{{ user.username }}</button>
                        <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="#">ユーザ情報</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                        </ul>
                    </div>
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="whole">
    <div class="container">
    {% include "_form.html" with submit_label="ログイン" %}
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<div class="whole">
    <div class="container">
        {% include "_form.html" with submit_label="ログイン" %}
    </div>
</div>
{% endblock %}

templates/answer/problemCreate.html
{% extends "base.html" %}
{% load static %}
{% block extrastatic %}
{% endblock %}
{% block content %}
{% include "_form.html" with submit_label="作成" %}
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/common/common.css' %}">
    {% block extrastatic %}
    {% endblock %}
    <title></title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

templates/home/home.html
{% extends "base.html" %}
{% load static %}
{% block extrastatic %}
<link rel="stylesheet" href="{% static 'css/home/home.css' %}">
{% endblock %}
{% block content %}
<div class="whole">
    {% include "_nav.html" %}
    <div class="container">
        <h1>ようこそ{{ user.username }}さん！</h1>
        <p class="home-p">最近作成した問題</p>
        <div class="row list-of-problems">
            {% for problem in problems %}
            <div class="col-6 left-problem problem">
                <p>{{ problem.japanese }}</p>
            </div>
            <div class="col-6 right-problem problem">
                <p>{{ problem.english }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}